# Generated by Django 5.0 on 2023-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_for_exams', '0003_alter_answeroption_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='score',
        ),
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='tests_for_exams.question'),
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
    ]
