# Generated by Django 5.0 on 2024-05-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_for_exams', '0005_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_images/'),
        ),
    ]
